# language: faust
language: generic
sudo: required
dist: trusty
before_script:
- sudo apt-get -qq update

# # install jackd2 from git
# - sudo apt-get build-dep libjack-jackd2-dev jackd2
# - git clone https://github.com/jackaudio/jack2.git /tmp/jack
# - pushd /tmp/jack
# - ./waf configure
# - ./waf build
# - sudo ./waf install

# # install faust from git
- sudo apt-get build-dep -yy faust
- git clone git://git.code.sf.net/p/faudiostream/code /tmp/faust
- pushd  /tmp/faust
- make
- sudo make install
- popd

# # install plugin-torture from git
- sudo apt-get install -yy  libboost-all-dev ladspa-sdk liblilv-dev lv2-dev libserd-dev libsord-dev libsratom-dev
- git clone https://github.com/cth103/plugin-torture.git /tmp/plugin-torture
- pushd /tmp/plugin-torture
- make
# - sudo make install
- sudo cp plugin-torture /usr/bin/
- popd

# # install lv2bm from git
# - wget https://github.com/moddevices/caps-lv2/raw/master/.create_lv2_env.sh
# - bash .create_lv2_env.sh
# - git clone https://github.com/moddevices/lv2bm
# - cd lv2bm && make && sudo make PREFIX=/usr install && cd ..
script:
- faust -v

# - faust CharacterCompressor.dsp

# # build jack console application
# - time faust2jackconsole  -t 9999999 -time -osc CharacterCompressor.dsp
# - jackd -vr -d dummy &
# - timeout 10 ./CharacterCompressor

# # build lv2
# - sudo apt-get install -yy libboost-all-dev
# - time faust2lv2  -t 9999999 -time CharacterCompressor.dsp

# - lv2bm `lv2ls`

# - plugin-torture --evil -d --lv2 --plugin $plugins/manifest.ttl | tee >(>> $DIR/lv2-evil.txt) | grep 'WARNING'

# # build ladspa
- time faust2ladspa  -t 9999999 -time CharacterCompressor.dsp
- ls
- plugin-torture --evil -d --ladspa --plugin CharacterCompressor.so

after_success:
- echo "Success!"

after_failure:
- echo "Something went wrong..."
notifications:
  email:
    on_success: never
    on_failure: never
