# language: faust
language: generic
sudo: required
dist: trusty
before_script:
- sudo apt-get install libasound2-dev
- git clone git://git.code.sf.net/p/faudiostream/code /tmp/faust
- pushd  /tmp/faust
- make
- sudo make install
- popd
# - export AUDIODEV=null
script:
- faust -v
- faust CharacterCompressor.dsp
- time faust2alsaconsole  -t 9999999 -time -osc CharacterCompressor.dsp
# - ./CharacterCompressor
after_success:
- echo "Success!"

after_failure:
- echo "Something went wrong..."
notifications:
  email:
    on_success: never
    on_failure: always
