# language: faust
language: generic
sudo: required
# addons:
#    apt:
#      sources:
#      # - debian-sid
#      - ubuntu-toolchain-r-test
#      packages:
#      - faust
before_script:
# - curl https://ftp-master.debian.org/keys/archive-key-5.0.asc | sudo apt-key add -
# - echo "deb http://ftp.us.debian.org/debian stable main contrib" | sudo tee -a /etc/apt/sources.list
- sudo add-apt-repository ppa:dr-graef/faust.trusty -y
- sudo apt-get -qq update
- sudo apt-get install --force-yes faust
script:
- faust -v
- faust CharacterCompressor.dsp
  #- faust2firefox CharacterCompressor.dsp
after_success:
- echo "Success!"

after_failure:
- echo "Something went wrong..."
