# language: faust
language: generic
sudo: required
dist: trusty
before_script:
- sudo apt-get build-dep libjack-jackd2-dev jackd2
- git clone https://github.com/jackaudio/jack2.git /tmp/jack
- pushd /tmp/jack
- ./waf configure
- ./waf build
- sudo ./waf install
- popd
- git clone git://git.code.sf.net/p/faudiostream/code /tmp/faust
- pushd  /tmp/faust
- make
- sudo make install
- popd
script:
- faust -v
- faust CharacterCompressor.dsp
- time faust2jackconsole  -t 9999999 -time -osc CharacterCompressor.dsp
- jackd -vr -d dummy &
- timeout 10 ./CharacterCompressor
after_success:
- echo "Success!"

after_failure:
- echo "Something went wrong..."
notifications:
  email:
    on_success: never
    on_failure: always
