# language: faust
language: cpp
install:  faust
script: 
            - faust2firefox CharacterCompressor.dsp                  
after_success:
            - echo "Success!"

after_failure:
            - echo "Something went wrong..."

        

