# language: faust
language: generic
sudo: required
before_install:
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo apt-get -qq update
- sudo apt-get install -y faust 
script: 
- faust CharacterCompressor.dsp                  
  #- faust2firefox CharacterCompressor.dsp                  
after_success:
- echo "Success!"

after_failure:
- echo "Something went wrong..."

        

