language: generic
sudo: required
dist: trusty

cache:
  directories:
  - $HOME/local

install:
  # build either the dependencies (1) and cache them, or build the dsp (0)
  - export BUILD_DEPS=1
  - bash travis/install_deps.sh

script:
  - faust -v
  - bash travis/build.sh

after_success:
  - echo "Success!"

after_failure:
  - echo "Something went wrong..."

notifications:
  email:
    on_success: never
    on_failure: never
