# language: faust
language: generic
sudo: required
dist: trusty
before_script:
- sudo apt-get install libjack-jackd2-dev jackd2 coreutils
- git clone git://git.code.sf.net/p/faudiostream/code /tmp/faust
- pushd  /tmp/faust
- make
- sudo make install
- popd
- jackd -vdr dummy &
script:
- faust -v
- faust CharacterCompressor.dsp
- time faust2jackconsole  -t 9999999 -time -osc CharacterCompressor.dsp
- timeout 10 ./CharacterCompressor
after_success:
- echo "Success!"

after_failure:
- echo "Something went wrong..."
notifications:
  email:
    on_success: never
    on_failure: always
