# language: faust
language: generic
sudo: required
dist: trusty
before_script:
# - sudo apt-get build-dep libjack-jackd2-dev jackd2
# - git clone https://github.com/jackaudio/jack2.git /tmp/jack
# - pushd /tmp/jack
# - ./waf configure
# - ./waf build
# - sudo ./waf install
- sudo apt-get build-dep -yy faust
- sudo apt-get install -yy  libboost-all-dev ladspa-sdk liblilv-dev lv2-dev libserd-dev libsord-dev libsratom-dev
# - sudo apt-get install ladspa-sdk
- git clone https://github.com/cth103/plugin-torture.git /tmp/plugin-torture
- pushd /tmp/plugin-torture
- make
- sudo make install
- popd
- git clone git://git.code.sf.net/p/faudiostream/code /tmp/faust
- pushd  /tmp/faust
- make
- sudo make install
- popd
script:
- faust -v
# - faust CharacterCompressor.dsp
# - time faust2jackconsole  -t 9999999 -time -osc CharacterCompressor.dsp
# - jackd -vr -d dummy &
# - timeout 10 ./CharacterCompressor
# - time faust2lv2  -t 9999999 -time CharacterCompressor.dsp
# - plugin-torture --evil -d --lv2 --plugin $plugins/manifest.ttl | tee >(>> $DIR/lv2-evil.txt) | grep 'WARNING'
- time faust2ladspa  -t 9999999 -time CharacterCompressor.dsp
- ls
- plugin-torture --evil -d --ladspa --plugin CharacterCompressor.so | tee >(>> ladspa-evil.txt) | grep 'WARNING'

after_success:
- echo "Success!"

after_failure:
- echo "Something went wrong..."
notifications:
  email:
    on_success: never
    on_failure: never
