# language: faust
language: generic
sudo: required
dist: trusty

# cache:
#   directories:
#   - /usr/bin

before_script:
- sudo apt-get -qq update
- mkdir -p $HOME/local/{bin,include,lib,share}

# # install faust from git
- echo "install faust"
- sudo apt-get build-dep -yy faust
- git clone git://git.code.sf.net/p/faudiostream/code /tmp/faust
- pushd  /tmp/faust
- make PREFIX=$HOME/local
- sudo make install
- popd

# # install jackd2 from git
# - echo "install jackd2"
# - sudo apt-get build-dep libjack-jackd2-dev jackd2
# - git clone https://github.com/jackaudio/jack2.git /tmp/jack
# - pushd /tmp/jack
# - ./waf configure
# - ./waf build
# - sudo ./waf install

# # install plugin-torture from git
- echo "install plugin-torture"
- sudo apt-get install -yy  libboost-all-dev ladspa-sdk liblilv-dev lv2-dev libserd-dev libsord-dev libsratom-dev
- git clone https://github.com/cth103/plugin-torture.git /tmp/plugin-torture
- pushd /tmp/plugin-torture
- make
- cp plugin-torture $HOME/local/
- popd

# # install lv2bm from git
- echo "install lv2bm"
- wget https://github.com/moddevices/caps-lv2/raw/master/.create_lv2_env.sh
- bash .create_lv2_env.sh
- git clone https://github.com/moddevices/lv2bm
- cd lv2bm && make && sudo make PREFIX=$HOME/local install && cd ..


script:
- sudo cp -r $HOME/local/ /usr/local/
- faust -v

# - faust CharacterCompressor.dsp

# # build jack console application
# - echo "building jack console application"
# - time faust2jackconsole  -t 9999999 -time -osc CharacterCompressor.dsp

# # build lv2
- echo "building lv2"
- time faust2lv2  -t 9999999 -time CharacterCompressor.dsp
- cp -r CharacterCompressor.lv2 ~/.lv2/

# # build ladspa
- echo "building ladspa"
- time faust2ladspa  -t 9999999 -time CharacterCompressor.dsp

- echo "starting tests"
# - jackd -vr -d dummy &
# - sleep 3
# - timeout 10 ./CharacterCompressor


- lv2bm `lv2ls`
# - lv2bm --full-test `lv2ls`

# - plugin-torture --evil -d --lv2 --plugin $plugins/manifest.ttl | tee >(>> $DIR/lv2-evil.txt) | grep 'WARNING'

- plugin-torture --evil -d --ladspa --plugin CharacterCompressor.so


after_success:
- echo "Success!"
- find /usr/local

after_failure:
- echo "Something went wrong..."
- find /usr/local

notifications:
  email:
    on_success: never
    on_failure: never
